### ISSUE TITLE
mac high sierra 打不开app

### ISSUE THREAD

**Issue by mygty21** [yangfeicheung/Shadowsocks-X#11]
如题，双击没反应，试着用terminal 打开显示：
2018-01-16 19:57:25.421 ShadowsocksX[9846:1363771] WARNING: NSUserDefaults has no server info
2018-01-16 19:57:25.533 ShadowsocksX[9846:1363777] http proxy start host=127.0.0.1, port=1081
DNS: couldn't parse name server 2001:558:feed::1.
logout
Saving session...

不知道是什么问题

**Comment by yangfeicheung** [comment]
您有没有把软件放在 /Applications 文件夹下面呢？ 之前发现如果文件夹的路径中间有空格，可能会导致打开有问题，比方说您放在桌面或者Downloads，有一定几率路径有空格，您把ShadowsocksX.app放到Applications文件夹，然后再打开试试，如果还有问题，请把问题截图发到我的邮箱，我帮您看下。

**Comment by yangfeicheung** [comment]
@mygty21  您试试最新版

**Comment by yangfeicheung** [comment]
@mygty21  最新的v2.12版本解决了一些crash的bug，您去下载试试？

**Comment by yangfeicheung** [comment]
@mygty21

**Comment by yangfeicheung** [comment]
please follow this instructions

https://www.sednax.com/faq-0.php
