### ISSUE TITLE
留学生模式没有生效

### ISSUE THREAD

**Issue by Lanfei** [yangfeicheung/Shadowsocks-X#12]
添加了一个国内服务器，全局模式时百度 IP 显示是国内，留学生模式时百度 IP 仍是国外。

**Comment by yangfeicheung** [comment]
留学生模式的时候，只有国内的网站才走server，如果您显示ip的网站是国外的，显示的自然是国外的ip地址，因为国外的ip地址并不需要翻墙走国内

**Comment by yangfeicheung** [comment]
有没有更新gfw列表之类的？ 这个模式之前用是正常的哦，是不是您根本没有配置socks代理导致的？用的是app store版本还是non app store版本？

**Comment by Lanfei** [comment]
更新了 gfw 也一样，也配置了代理，就像我说的，全局模式百度显示 IP 是国内，而留学生模式仍是国外，版本是 GitHub 最新版本。

**Comment by yangfeicheung** [comment]
@Lanfei 我测试了下，我这边是可以正常显示的，您下载最新版试试，另外，有时会ip数据库显示的不一定100%准确

**Comment by yangfeicheung** [comment]
@Lanfei 我测试了下，我这边是可以正常显示的，您下载最新版试试，另外，有时会ip数据库显示的不一定100%准确

**Comment by yangfeicheung** [comment]
@Lanfei 澳洲那边测试是可以的

**Comment by yangfeicheung** [comment]
@Lanfei  不好意思，这个是一个bug，已经发现了，在最新的版本中，已经修复了，您可以下载最新的版本检验一下，如果还有问题，请联系我。

**Comment by Lanfei** [comment]
OK，更新了版本和 GFW 列表后正常了，感谢！

**Comment by yangfeicheung** [comment]
好的
