### ISSUE TITLE
在外面显示的功能按钮太多了，好多都不经常用到

### ISSUE THREAD

**Issue by SucreYang** [yangfeicheung/Shadowsocks-X#14]
对于小白用户，简单最重要，可以把一些用户不经常用的功能按钮放在【设置】里面，这样页面会清爽不少；同时可以把服务器购买菜单放到到外面，增加曝光量。

**Comment by yangfeicheung** [comment]
好的，下一个版本会加以改进，多谢提意见

**Comment by yangfeicheung** [comment]
@SucreYang  最新版本已经进行了更改，您重新下载试试
