### ISSUE TITLE
频繁提示 “正在尝试修改系统网络配置 键入密码以允许执行此操作”

### ISSUE THREAD

**Issue by mayu2010** [yangfeicheung/Shadowsocks-X#16]
问题现象如下：
    软件启动/退出、打开/关闭ShadowSocks、切换状态等操作都会弹出输入密码的窗口。非常烦，希望给一些解决的建议。

Shadowsocks-X版本 2.11 (21)，检查更新-提示已经是最新版本

安装在/Users/[用户名]/Application路径下，文件夹权限为
 drwxr-xr-x  3 [用户名]  staff   102B  1 23 17:31 ShadowsocksX.app

系统MacOSX 10.11.6 EI Capitan

以前几个月无此问题，近2天出现。根据回忆，用CleanMyMac清理过系统、修复过磁盘权限。不知是否与此有关，如何处理。

**Comment by mayu2010** [comment]
<img width="449" alt="2018-01-24 9 22 54" src="https://user-images.githubusercontent.com/11343398/35311610-5389b374-00f2-11e8-9058-77476ab733d1.png">

**Comment by yangfeicheung** [comment]
@mayu2010 建议你放到根目录的 /Applications 这个文件夹下面，问题的原因可能出在，您的路径  /Users/[用户名]/Application  中间有空格，导致配置网络的功能失败，所以会不停的请求，您把App挪到  /Applications目录下试试

**Comment by mayu2010** [comment]
可以确认之前的路径中间也没有空格，应该不是空格引起的问题。

将软件卸载，重新安装一次。所有的操作为：
0. 清理相关的配置文件
1. 下载release包：https://github.com/yangfeicheung/Shadowsocks-X/releases/download/2.11/ssx-mac-v21.zip
2. 解压到根目录下的/Application。这次不是放在家目录下。
3. 结果依然不停地弹输入密码的窗口，困惑。
4. 软件运行后已经恢复到了最初的默认配置，之前自行导入的服务器配置信息确实已经没了，应该能排除残留配置文件的影响。

**Comment by yangfeicheung** [comment]
@mayu2010  您方便微信发我邮箱一下么，我加您一下看看

**Comment by Pudge1996** [comment]
刚刚我修改了磁盘文件的权限，导致切换 SS 会弹出题主所描述的提示框，但是解决了。
进入资源库/Application Support 删除里面的ShadosocksX-NG文件夹，然后 SS 会被强制退出，再次打开 SS 就好了。

**Comment by yangfeicheung** [comment]
ok, I'm glad that it's fixed

**Comment by shuvigoss** [comment]
@mayu2010 解决了吗？我现在也是这个问题，每次要求输入2遍。。。

**Comment by yangfeicheung** [comment]
已经解决了，您联系下我mail,我发图帮您解决

**Comment by shuvigoss** [comment]
@mayu2010 我的解决了，具体原因我不太清楚

打开terminal 输入：
cd ~/Library/Application\ Support/ShadowsocksX-App/
curl -O https://www.sednax.com/files/app-installer
sudo chmod +s app-installer; sudo chmod +s ss-netconfig

**Comment by yangfeicheung** [comment]
@mayu2010
@shuvigoss
please run these two as well: 

sudo chown root:admin app-installer
sudo chown root:admin ss-netconfig

**Comment by ykla** [comment]
按照以上步骤，仍未解决 。MAC 10.13

**Comment by yangfeicheung** [comment]
@ykla  @NateRobinson
應該是命令沒有執行正確把，確保上面的命令一條一條都執行正確了，肯定沒問題哦。
如果有問題，請把聯繫方式發到我郵箱，我face to face教一下

**Comment by NateRobinson** [comment]
@yangfeicheung  重新下了客户端ok了

**Comment by linglong117** [comment]
我也是手贱，用CleanMyMac 修复过权限，就成这样了，之前都正常的；

**Comment by yangjun616** [comment]
上面的链接都已经无法下载了

**Comment by yangfeicheung** [comment]
open Terminal app on mac
please run the following commands in Terminal in order, basically, it's the permission issue:

curl -O https://www.emptyus.com/files/ss-repair.sh;
chmod a+x ss-repair.sh;
./ss-repair.sh;
