### ISSUE TITLE
Commit message

### ISSUE THREAD

**Issue by qinyuhang** [yangfeicheung/Shadowsocks-X#2]
If U really want to contribute to the project, just create a fork from the original fork, instead of upload and erease all others commits.
If U do so, there is too disadvantage:
1st, makes other harder to find out how the app is developed and harder to debug or find out what U have modified.
2nd, disrespect of all other contributor, U erease their contributes.

**Comment by yangfeicheung** [comment]
Thanks for concerning, I'm new to github,although I used to use it as a source of code, to be honest,I even tried to learn how to use it.Anyway,sorry for the mess,I would check how to sort it out.

**Comment by qinyuhang** [comment]
Whats the update of UR “sort it out”？Y U erase other contributors' commits.

**Comment by jumeow** [comment]
According to your pinned repos, i thought you know how to fork a repo. One of the easy solutions is delete this repo, and fork from the source, then add your commits to it.
