### ISSUE TITLE
为什么下载后不能运行？

### ISSUE THREAD

**Issue by charlie-charlie** [yangfeicheung/Shadowsocks-X#24]
我的Mac OS：10.33.2
我下载的是：http://www.sednax.com/data/ssx-mac-v22.zip
下载到Downloads, 我把它移到 "Applications", 点击后提示我密码，然后就没有了。没有弹出任何窗口。我用ps, 看见shadowsocksX在运行。但是因为没有弹出窗口，我不知道大家在哪里设定“modes“，很显让不是通过命令行该配置文件。
多谢！

**Comment by charlie-charlie** [comment]
请看，进程在运行。
ps -ef|grep -i Shadow
  501  3164     1   0  8:31pm ??         0:00.54 /Applications/ShadowsocksX-NG.app/Contents/MacOS/ShadowsocksX-NG
  501  4191     1   0  8:59pm ??         0:00.26 /Applications/ShadowsocksX.app/Contents/MacOS/ShadowsocksX -psn_0_712878

**Comment by charlie-charlie** [comment]
我认为我知道原因了。我看见shadowsocks icon了。多谢！

**Comment by yangfeicheung** [comment]
@charlie-charlie  在顶部的菜单栏目里面呢

![image](https://user-images.githubusercontent.com/33145750/35721336-62a566f0-082c-11e8-8bb1-8da4450e7753.png)
