### ISSUE TITLE
simple-obfs?

### ISSUE THREAD

**Issue by jibon57** [yangfeicheung/Shadowsocks-X#29]
Hi,

Is it possible to add support for simple-obfs plugin?

Ref: https://github.com/shadowsocks/ShadowsocksX-NG/pull/587

Thanks

**Comment by yangfeicheung** [comment]
yup, planning,

**Comment by jibon57** [comment]
@yangfeicheung Thank you !! Waiting for it..

**Comment by jibon57** [comment]
@yangfeicheung any update?

**Comment by jibon57** [comment]
Got it here: https://github.com/shadowsocks/ShadowsocksX-NG
