### ISSUE TITLE
Scan Screen QR Code Not Working

### ISSUE THREAD

**Issue by Guzzii** [yangfeicheung/Shadowsocks-X#4]
Nothing happens after triggering it. I am using the app store version. Let me know if you need any other information for debugging.

**Comment by yangfeicheung** [comment]
please send me a qr code that does not working to my email: yangfei.cheung@gmail.com

**Comment by yangfeicheung** [comment]
@Guzzii ?

**Comment by yangfeicheung** [comment]
I've fixed the issue,if u do have problems,open a new issue pls

**Comment by Guzzii** [comment]
Thank you very much for fixing the issue. The new release works flawlessly for me now. Sorry for late reply. Have been traveling quite a bit recently.

**Comment by yangfeicheung** [comment]
Glad to hear that,happy new year^_^
