### ISSUE TITLE
导入服务器之后我在哪看我导入的服务器信息呢？？？

### ISSUE THREAD

**Issue by wustwg** [yangfeicheung/Shadowsocks-X#42]
我是自己买的vps服务器，但是我导入之后找不到我的设备。而且我也没购买就能用了，这是因为我导入了所以我就能用了？？？？我的设备是被共享了吗？

**Comment by yangfeicheung** [comment]
hi，不是的，我們默認有15天的試用期，您可以免費使用15天，然後再決定是否購買的。

**Comment by yangfeicheung** [comment]
如果您找不到您導入的vps服務器，可能是因為您用了不兼容的二維碼導入，您可以選擇
服務器-》編輯服務器  然後手動添加
