### ISSUE TITLE
Loses connection occasionally

### ISSUE THREAD

**Issue by jarnanchen** [yangfeicheung/Shadowsocks-X#44]
Found in Version 2.16:
Sometimes the app will cause net interruption in chrome, even when trying to access mainland websites.After waiting a while it could go back to normal.
Restarting the app will fix it. However the issue will occur again after some minutes.

**Comment by yangfeicheung** [comment]
Sorry about the trouble, this is a bug and we will try to fix it in the future version, we also noticed that if you change servers frequently in a short period of time,  it's very likely you would meet this problem, however, normally there's no need to do that frequently, so our suggestion now is,  close app and reopen to fix this issue for now,  sorry again about the trouble, if this happens a lot and  you enable high availability mode, please disable high availability mode.

**Comment by yangfeicheung** [comment]
The  latest version have fixed this issue,please update.

**Comment by yangfeicheung** [comment]
Please let me know if this issue still exists
