### ISSUE TITLE
长时间盖盖后无法连接网络

### ISSUE THREAD

**Issue by mojie126** [yangfeicheung/Shadowsocks-X#45]
RT，不论是重新连接wifi还是移除wifi配置重新连接都不行，就是提示没有网络

重启或关掉该软件后就可以了...

**Comment by yangfeicheung** [comment]
what version do you use? I remember that I have fixed this issue, could you please try the latest version and test it again?

**Comment by mojie126** [comment]
英语不太好，我下的就是最新版本...2.16版本...

**Comment by mojie126** [comment]
好的，谢谢...

**Comment by yangfeicheung** [comment]
@mojie126
嘗試下最新的版本哦,已經修復了,您試試

**Comment by mojie126** [comment]
好的...我试试看...

**Comment by yangfeicheung** [comment]
please let me know if this problem still exists

**Comment by jokeroy** [comment]
@yangfeicheung 还是一样，时间一长就会断，要重新启动才能继结连接

**Comment by yangfeicheung** [comment]
請更新到2.17（27）這個版本，已經修復了這個問題
