### ISSUE TITLE
YouTube  无法显示

### ISSUE THREAD

**Issue by sandersxx** [yangfeicheung/Shadowsocks-X#49]
为什么我用Chrome Canary开启YouTube后正常连线
但10秒后他就会无法显示
<img width="728" alt="2018-06-13 5 46 15" src="https://user-images.githubusercontent.com/40233025/41343633-b1b529c6-6f31-11e8-8f67-ccc49ba9f5bc.png">

**Comment by yangfeicheung** [comment]
chrome有些代理插件，和app有衝突，不可以同時用，請看下面的介紹，一般禁止掉插件就可以正常使用了，您可以用safari做對比測試：

https://www.sednax.com/faq-1-cn.php

**Comment by sandersxx** [comment]
謝謝已解決了

Sent from my iPhone

On 21 Jun 2018, at 15:04, Yangfei <notifications@github.com<mailto:notifications@github.com>> wrote:


chrome有些代理插件，和app有衝突，不可以同時用，請看下面的介紹，一般禁止掉插件就可以正常使用了，您可以用safari做對比測試：

https://www.sednax.com/faq-1-cn.php
