### ISSUE TITLE
源码ios版是不是缺少文件,报错

### ISSUE THREAD

**Issue by alongmatch** [yangfeicheung/Shadowsocks-X#5]
clang: error: no such file or directory: '**********Shadowsocks-X/ShadowWeb/table.m'
clang: error: no input files

**Comment by ewrfedf** [comment]
table.m

**Comment by ewrfedf** [comment]
@alongmatch pod install 拉取下代码资源应该可以 没有测试

**Comment by alongmatch** [comment]
好的.我去试一下

**Comment by yangfeicheung** [comment]
ios version is unable to work because it is written  like  on ios7 or older ones,it does not work on latest ios
