### ISSUE TITLE
Not working on osX.

### ISSUE THREAD

**Issue by MingrenChen** [yangfeicheung/Shadowsocks-X#53]
Logs on PC shows shadowsocks X connected successful, however, IP address not changing under global mode.
[![Pk0Pcd.md.png](https://s1.ax1x.com/2018/07/01/Pk0Pcd.md.png)](https://imgchr.com/i/Pk0Pcd)

Logs on server side show that my Macbook did connect to shadowsocks.
[![Pk0fvd.md.png](https://s1.ax1x.com/2018/07/01/Pk0fvd.md.png)](https://imgchr.com/i/Pk0fvd)

This also happened on original shadowsocks-NG, but connections work fine from Android8 and iOS9.

**Comment by lujiwen** [comment]
It also happened to me, I haven been spent too many day on fixing this problem, and I am sure It is not caused by server side, my another client on win10 works well.

**Comment by yangfeicheung** [comment]
Please make sure that there's no extension conflicts:

https://www.sednax.com/faq-1.php

**Comment by MingrenChen** [comment]
Yes, it conflict with unblock youku and works fine after turn off unblock youku.

**Comment by yangfeicheung** [comment]
Please check the menu "How To", it has solutions for most common issues there. Thanks for your feedback and please let us know if any.

**Comment by lujiwen** [comment]
I fix this problem by disable system integrity protection, please refer to this https://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/
Hopping to help !
