### ISSUE TITLE
无法购买服务

### ISSUE THREAD

**Issue by tommy7539** [yangfeicheung/Shadowsocks-X#6]
<img width="540" alt="2017-12-28 15 12 38" src="https://user-images.githubusercontent.com/11268054/34403192-726c9bd0-eb6c-11e7-9280-c83649be93cf.png">
<img width="544" alt="2017-12-28 15 12 54" src="https://user-images.githubusercontent.com/11268054/34403194-72bcee96-eb6c-11e7-9916-8d69e1b0cb9b.png">
<img width="544" alt="2017-12-28 15 13 06" src="https://user-images.githubusercontent.com/11268054/34403195-72ed66d4-eb6c-11e7-9240-b3c563399c97.png">
通过菜单：服务器-购买服务器，之后会出错。
不知道如何购买？

**Comment by yangfeicheung** [comment]
please contact me via my email:  yangfei.cheung@gmail.com
