### ISSUE TITLE
couldn't launch Shadowsocks v2.2 on macOS sierra 10.12.6

### ISSUE THREAD

**Issue by hegw** [yangfeicheung/Shadowsocks-X#64]
I fellow this instrunction: https://www.sednax.com/faq-0.php
removed the old version v2.16，and added the latest v2.2 to /Applications , but I could not launch ShadowsockX, no response, no tip info.

when i install the old version v2.16 from AppStore, it works.

**Comment by yangfeicheung** [comment]
try to use the new version v2.21
