### ISSUE TITLE
The 2.21 doesn't work

### ISSUE THREAD

**Issue by a13519** [yangfeicheung/Shadowsocks-X#66]
The latest 2.21 does work on the mac pro 10.13.6 (17G3025), it just keeps busy by showing the busy bar for ever. please fix.

**Comment by hegw** [comment]
if you removed the old version, then remove the file /Users/{your user name }/Library/Preferences/com.jumboapps.shadowsocksx.plist, try again.

**Comment by yangfeicheung** [comment]
please update to latest version v2.22
