### ISSUE TITLE
Youtube访问很快，但终端下载就很慢，比如brew update

### ISSUE THREAD

**Issue by sandychales** [yangfeicheung/Shadowsocks-X#68]
终端下载东西很慢，复制了HTTP代理命令到终端，依然很慢，比如执行brew update

**Comment by totoroyyb** [comment]
终端默认不走代理，可以添加以下代理规则至 `~/.bash_profile`

> export http_proxy=socks5://127.0.0.1:1080
> export https_proxy=socks5://127.0.0.1:1080

端口根据自己设定的更改

**Comment by luvvien** [comment]
@sandychales 终端不走ss，可以尝试用outline，Google母公司出的一个神器，，命令行也可以用Apple store就能下载。搭建方法可以参考 https://vien.tech/article/103

**Comment by sandychales** [comment]
> 终端默认不走代理，可以添加以下代理规则至 `~/.bash_profile`
> 
> > export http_proxy=socks5://127.0.0.1:1080
> > export https_proxy=socks5://127.0.0.1:1080
> 
> 端口根据自己设定的更改

多谢，后来发现必须改成全局模式，才能访问github上的资源

**Comment by sandychales** [comment]
> @sandychales 终端不走ss，可以尝试用outline，Google母公司出的一个神器，，命令行也可以用Apple store就能下载。搭建方法可以参考 https://vien.tech/article/103

多谢指引！

**Comment by luvvien** [comment]
> > @sandychales 终端不走ss，可以尝试用outline，Google母公司出的一个神器，，命令行也可以用Apple store就能下载。搭建方法可以参考 https://vien.tech/article/103
> 
> 多谢指引！

好像链接给错了 是 [outline](https://vien.tech/article/93)

**Comment by yangfeicheung** [comment]
@totoroyyb  is right, the Terminal by default doesn't use  shadowsocksx connection, so please choose menu "Enable HTTP Proxy", and then copy http proxy command to your terminal
