### ISSUE TITLE
自动退出

### ISSUE THREAD

**Issue by dargonjack** [yangfeicheung/Shadowsocks-X#7]
打开应用几秒种后会自动退出,mac

**Comment by yangfeicheung** [comment]
可以提供详细点的信息么？比如说系统版本？ 软件版本？

**Comment by dargonjack** [comment]
系统和软件都是最新的，原因我测试出来了。选择了高可用性重启电脑以后会有这个问题，重新勾选就又可以用了

**Comment by yangfeicheung** [comment]
好的，不好意思，可能是由于软件的某个bug没有测试到位，带来的不便，深感歉意，如果后续还是继续出现这种情况，还希望您能多提供相关信息，谢谢您的支持。
