### ISSUE TITLE
mac新手 安装后应用中心没有 在哪里找到运行文件？

### ISSUE THREAD

**Issue by clown-wang** [yangfeicheung/Shadowsocks-X#70]
如题 默认安装路径在哪里 先谢大佬

**Comment by luvvien** [comment]
@clown-wang 解压后就直接能运行啊。你可以打开finder然后拖到 application中。关于ss服务端搭建教程请参考 https://vien.tech/tag/53

**Comment by yangfeicheung** [comment]
Pls check this:
https://www.sednax.com/faq-12.php
