### ISSUE TITLE
白名单模式

### ISSUE THREAD

**Issue by weather319** [yangfeicheung/Shadowsocks-X#8]
能否支持大陆白名单模式，根据Ip地址自动进行判断？

**Comment by yangfeicheung** [comment]
可以的，上面的黑名单模式就是您所谓的白名单模式，大陆的ip会自动识别走ss的服务器，需要搭配一个大陆的服务器

![image](https://user-images.githubusercontent.com/33145750/34599204-0d5ad902-f22c-11e7-865f-a7c1cb8229d2.png)
