### ISSUE TITLE
很棒，支持作者，请问有捐赠方式吗？我想捐赠一下

### ISSUE THREAD

**Issue by ssrpanel** [yangfeicheung/Shadowsocks-X#9]
如题

**Comment by ssrpanel** [comment]
哦对了，请问可以生成dmg文件吗？下载下来都是源码。。。不懂编译

**Comment by winstonlin917** [comment]
我在一个网络代理平台买了个套餐，网站给了我个json文件让我以服务器配置文件导入shadowsocks，还给了我端口，密码，节点列表等等，我该怎么在你的改版上用？我实在不知咋搞。谢谢大大！

**Comment by yangfeicheung** [comment]
@ssrpanel  您可以直接下载编译好的版本，直接使用，下载地址如下：
https://github.com/yangfeicheung/Shadowsocks-X/releases

**Comment by yangfeicheung** [comment]
@winstonlin917  可以在编辑服务器那里手动一个一个填入，或者选择从json文件导入试试

![image](https://user-images.githubusercontent.com/33145750/34640726-095b7890-f333-11e7-82d7-6b1ed9deb7ba.png)
