### ISSUE TITLE
是不是现在VPN都无法使用了？？

### ISSUE THREAD

**Issue by NEOscavenger00** [yangfeicheung/Shadowsocks-X#90]
我试了所有节点，一直都是timeout，无法打开谷歌和其他网站，有没有和我一样的，关键是我才买的啊，加了微信问，也没有人回复，，伤心 啊。。。。。

**Comment by LIE9707** [comment]
70大庆 特殊时期管控加强了 应该。

**Comment by shulijiang** [comment]
我也是，刚刚买了发现打不开，唉太难受了

**Comment by francoly** [comment]
why does it can’t work

**Comment by francoly** [comment]
why does it can’t work

**Comment by xhb** [comment]
我也是刚刚买啊，谁来赔偿我们的损失？？？

**Comment by sallecyan** [comment]
大家好 有想要梯子的可以联系我 v-137101316

**Comment by jlcool** [comment]
自己搞的服务器都被封了，难道有针对ss的封锁？

**Comment by yangfeicheung** [comment]
fixed, please update to latest version
